### ISSUE TITLE
php7 and constructors

### ISSUE THREAD

**Issue by vpil** [thoroc/php_writeexcel#7]
For php v7 compatibility it is needed to get rid of php v4-style constructors. ie.
replace
`public function writeexcel_worksheet(...`
with
`public function __construct(...`

And appropriate calls, ie:
replace
`$this->writeexcel_biffwriter();`
with
`parent::__construct();`

Thank you

**Comment by thoroc** [comment]
Committed a php5+ branch with the `__construct()` change requested. I haven't got the time to test it properly. Could you try it and let me know?

**Comment by vpil** [comment]
Just one more constructor rename in class.writeexcel_worksheet.inc and everything seems OK. Thank you.

**Comment by thoroc** [comment]
Sorry didn't see that one :/
